--- 
server: 
  port: 8989
  servlet: 
    context-path: /webcrawlerservice
spring: 
  data: 
    mongodb: 
      database: webcrawler
      host: localhost
      port: 27017
crawler-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8990
    ServerListRefreshInterval: 15000
redis:
  host: localhost
  port: 6379